name: Update Stream Data

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run scraper
      env:
        ZJUAM_USERNAME: ${{ secrets.ZJUAM_USERNAME }}
        ZJUAM_PASSWORD: ${{ secrets.ZJUAM_PASSWORD }}
      run: python update_db.py

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add stream_db.json
        git commit -m "Auto-update stream data" || echo "No changes to commit"
        git push